"""Electrostatic features augmented by a dynamic, disjoint source set.

This module provides the feature-side analogue of
:mod:`graph_longrange.external_source_energy`.  The wrapper keeps the normal
same-set features and adds the potential generated by external sources at the
wrapped block's target nodes.  It contains no MACE or OpenMM-specific logic.
"""

from __future__ import annotations

from typing import Optional

import torch

from .features import FeaturePBCHandling, GTOElectrostaticFeatures


class GTOElectrostaticExternalSourceFeatures(torch.nn.Module):
    """Add a dynamic source-to-target field to a GTO feature block.

    External tensors use graph_longrange's ``multipoles`` normalization and
    e3nn component ordering.  They are supplied per evaluation with
    :meth:`set_external_sources` and are deliberately not registered as model
    buffers or checkpoint state.

    ``external_scale`` lets a caller split a physical external potential
    across several channels.  Its default is one; PolarMACE, for example, uses
    one half for each of its alpha and beta channels.
    """

    _EXTERNAL_FIELD_CACHE_KEY = "_graph_longrange_external_field"

    def __init__(
        self,
        base: GTOElectrostaticFeatures,
        external_scale: float = 1.0,
    ) -> None:
        super().__init__()
        self.base = base
        self.external_scale = float(external_scale)
        self._external_feats: Optional[torch.Tensor] = None
        self._external_positions: Optional[torch.Tensor] = None
        self._external_batch: Optional[torch.Tensor] = None

    @classmethod
    def from_features(
        cls,
        features: GTOElectrostaticFeatures,
        external_scale: float = 1.0,
    ) -> "GTOElectrostaticExternalSourceFeatures":
        """Wrap an existing feature block without changing its parameters."""
        return cls(features, external_scale=external_scale)

    def __getattr__(self, name):
        try:
            return super().__getattr__(name)
        except AttributeError:
            return getattr(self.base, name)

    def set_pbc_handling(self, pbc_handling: FeaturePBCHandling) -> None:
        self.base.set_pbc_handling(pbc_handling)

    def set_external_sources(
        self,
        external_feats: Optional[torch.Tensor] = None,
        external_positions: Optional[torch.Tensor] = None,
        external_batch: Optional[torch.Tensor] = None,
    ) -> None:
        """Set one evaluation's external sources, or clear them with all ``None``."""
        values = (external_feats, external_positions, external_batch)
        if all(value is None for value in values):
            self.clear_external_sources()
            return
        if any(value is None for value in values):
            raise ValueError(
                "external_feats, external_positions and external_batch must "
                "either all be provided or all be None."
            )
        self._external_feats = external_feats
        self._external_positions = external_positions
        self._external_batch = external_batch

    def clear_external_sources(self) -> None:
        self._external_feats = None
        self._external_positions = None
        self._external_batch = None

    @staticmethod
    def _normalise_source_feats(source_feats: torch.Tensor) -> torch.Tensor:
        if source_feats.dim() == 3 and source_feats.shape[-2] == 1:
            return source_feats.squeeze(-2)
        return source_feats

    def _external_field(self, geometry: dict) -> Optional[torch.Tensor]:
        if self._external_feats is None:
            return None
        cache = self.base.precompute_geometry_source_target(
            k_vectors=geometry["k_vectors"],
            k_norm2=geometry["k_norm2"],
            k_vector_batch=geometry["k_vector_batch"],
            k0_mask=geometry["k0_mask"],
            src_positions=self._external_positions,
            src_batch=self._external_batch,
            tgt_positions=geometry["node_positions"],
            tgt_batch=geometry["batch"],
            volume=geometry["volume"],
            pbc=geometry["pbc"],
        )
        return self.base.forward_dynamic_source_target(
            cache=cache,
            source_feats=self._external_feats,
        )

    def precompute_geometry(self, **kwargs) -> dict:
        """Precompute normal geometry and, when set, the external field."""
        base_kwargs = dict(kwargs)
        # Older host models may still pass this retired graph_longrange option.
        base_kwargs.pop("force_pbc_evaluator", None)
        cache = self.base.precompute_geometry(**base_kwargs)
        if self._external_feats is None:
            return cache
        external_field = self._external_field(base_kwargs)
        result = dict(cache)
        result[self._EXTERNAL_FIELD_CACHE_KEY] = external_field
        return result

    def forward_dynamic(
        self,
        cache: dict,
        source_feats: torch.Tensor,
        pbc: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """Return same-set features plus the cached external contribution."""
        del pbc  # Accepted for compatibility with older host model calls.
        value = self.base.forward_dynamic(
            cache=cache,
            source_feats=self._normalise_source_feats(source_feats),
        )
        external_field = cache.get(self._EXTERNAL_FIELD_CACHE_KEY)
        if external_field is not None:
            value = value + self.external_scale * external_field
        return value

    def forward(self, **kwargs) -> torch.Tensor:
        """Evaluate both geometry and features in a single call."""
        source_feats = kwargs["source_feats"]
        geometry = dict(kwargs)
        geometry.pop("source_feats")
        cache = self.precompute_geometry(**geometry)
        return self.forward_dynamic(cache=cache, source_feats=source_feats)


__all__ = ["GTOElectrostaticExternalSourceFeatures"]
